.TH IPT-FIREWALL 8 "" "February 2016" "ipt-firewall 1.0.0"
.SH NAME
ipt-firewall \- simple firewall
.SH SYNOPSIS
\fBipt-firewall\fP [\fBOPTIONS\fP] \fBCOMMAND\fP
.SH DESCRIPTION
\fBipt-firewall\fP is a simple iptables/ip6tables and ebtables control script
that clears previous rules and sets up a firewall from user defined rule
files.
.SH RULES
Rule files (files ending with \fI.rules\fP) are read from
\fI\/etc/firewall.d/\fP and each line evaluated before added as a firewall rule.
Only lines starting with ${ are used, and any lines containing any of the
patterns \fI.*;.*\fP, \fI\\$\(.*\)\fP, \fI([&]|[|])\fP, \fI[\\`]\fP is discarded
(and produces a log message and/or warning depending on options used).
.PP
A rule that would normally start with \fB/sbin/iptables\fP or \fBiptables\fP
should be defined with \fB${IPT4}\fP instead. \fBip6tables\fP and
\fBebtables\fP respectively should use \fB${IPT6}\fP and \fB${EBT}\fP.
.SH EXCLUSIONS
Chains that are handled by another application or for any other reason should
not be flushed and destroyed by \fBipt-firewall\fP can be excluded in
\fIipt4-chains.exclude\fP and/or \fIipt6-chains.exclude\fP under
\fI/etc/firewall.d/\fP. These files takes the name of one chain per line.
.SH OPTIONS
.TP
.B \-6
Enable ip6tables in rule files.
.TP
.B \-e
Enable ebtables in rule files. Experimental.
.TP
.B \-i
Log illegal lines encountered in rule files.
.TP
.B \-l LEVEL
Set log level to \fBLEVEL\fP. Allowed values are 2-6, default is 4. Levels are
inclusive with all lower levels. The numbers correspond to:
    6 debug
    5 notice
    4 info
    3 warning
    2 error
.TP
.B \-V
Verbose, show all available output.
.TP
.B \-s
Silent, output nothing but a few error messages.
.TP
.B \-I POLICY
Set a pseudo-policy for the INPUT chain. The actual policy of the built in
chains remain ACCEPT, but after loading all rules the chain is appended with
\'\-A INPUT \-j \fBPOLICY\fP\'.
.TP
.B \-F POLICY
Set a pseudo-policy for the FORWARD chain. The actual policy of the built in
chains remain ACCEPT, but after loading all rules the chain is appended with
\'\-A FORWARD \-j \fBPOLICY\fP\'.
.TP
.B \-O POLICY
Set a pseudo-policy for the OUTPUT chain. The actual policy of the built in
chains remain ACCEPT, but after loading all rules the chain is appended with
\'\-A OUTPUT \-j \fBPOLICY\fP\'.
.TP
.B \-h
Show help and exit
.TP
.B \-v
Show version and exit

.SH SEE ALSO
iptables(8), ip6tables(8), ebtables(8)
